/*
 * Parallax Mouse Interaction v2.0
 *
 * Copyright 2012-2021, LambertGroup
 *
*/


(function(d){function la(a,b,e){var m=Y();if(e.responsive){var l="";if(-1!=a.css("font-size").lastIndexOf("px")){var f=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("px"));l+="font-size:"+f/(e.origWidth/e.width)+"px;"}else-1!=a.css("font-size").lastIndexOf("em")&&(f=a.css("font-size").substr(0,a.css("font-size").lastIndexOf("em")),l+="font-size:"+f/(e.origWidth/e.width)+"em;");-1!=a.css("line-height").lastIndexOf("px")?(f=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("px")),
l+="line-height:"+f/(e.origWidth/e.width)+"px;"):-1!=a.css("line-height").lastIndexOf("em")&&(f=a.css("line-height").substr(0,a.css("line-height").lastIndexOf("em")),l+="line-height:"+f/(e.origWidth/e.width)+"em;");a.wrapInner('<div class="newFS" style="'+l+'" />')}l=a.attr("data-final-left");f=a.attr("data-final-top");e.responsive&&(l=parseInt(l/(e.origWidth/e.width),10),f=parseInt(f/(e.origWidth/e.width),10));if("true"!=a.attr("data-preanimate")){var k=e.defaultEasing;""!=a.attr("data-easing")&&
void 0!=a.attr("data-easing")&&(k=a.attr("data-easing"));var h=1;1==b.isVideoPlaying&&(h=0);-1!=m&&9>m&&a.css({opacity:1});a.stop().animate({opacity:h,left:l+"px",top:f+"px"},1E3*a.attr("data-duration"),k,function(){1==b.isVideoPlaying&&d(b.currentImg.attr("data-text-id")).children().css("opacity",0);b.textInPlace[b.textInPlace.length]=1;void 0!=a.attr("data-continuous-left")&&""!=a.attr("data-continuous-left")&&(ba(a,b,e),b.continuouseIntervalIDs[b.continuouseIntervalIDs.length]=setInterval(function(){ba(a,
b,e)},1E3*a.attr("data-continuous-duration")));(-1==m||-1!=m&&9<=m)&&void 0!=a.attr("data-rotate")&&""!=a.attr("data-rotate")&&"true"==a.attr("data-rotate")&&(rotDuration=.5,void 0!=a.attr("data-rotate-duration")&&""!=a.attr("data-rotate-duration")&&(rotDuration=a.attr("data-rotate-duration")),b.rotationDurationArr[a.index()]=rotDuration,b.rotationFunctionsArr[a.index()]=function(){b.rotationFunctionsArr.length&&void 0!=b.rotationDurationArr[a.index()]&&""!=b.rotationDurationArr[a.index()]&&a.rotate({angle:0,
animateTo:360,duration:1E3*b.rotationDurationArr[a.index()],callback:b.rotationFunctionsArr[a.index()],easing:function(t,y,w,v,n){return y/n*v}})},b.rotationFunctionsArr[a.index()]())})}else a.css({left:l+"px",top:f+"px",opacity:1}),b.textInPlace[b.textInPlace.length]=1}function T(a,b,e,m,l,f,k){b=d(b.attr("data-text-id")).children();var h,t,y=0,w=[];k?d(".newFS",l).contents().unwrap():a.textInPlace.length=0;b.each(function(){w[y]=d(this);var v=w[y];k&&"true"==v.attr("data-preanimate")?(v.css({display:"block"}),
h=v.attr("data-final-left"),t=v.attr("data-final-top"),e.responsive&&(h=parseInt(h/(e.origWidth/e.width),10),t=parseInt(t/(e.origWidth/e.width),10)),v.css({left:h+"px",top:t+"px",opacity:1,display:"block"})):k?v.css({display:"none",opacity:0}):v.css({display:"block"});"true"!=v.attr("data-preanimate")&&(h=v.attr("data-initial-left"),t=v.attr("data-initial-top"),e.responsive&&(h=parseInt(h/(e.origWidth/e.width),10),t=parseInt(t/(e.origWidth/e.width),10)),v.css({left:h+"px",top:t+"px",opacity:parseInt(v.attr("data-fade-start"),
10)/100}));k||(a.timeouts_arr[a.timeouts_arr.length]=setTimeout(function(){la(v,a,e)},1E3*v.attr("data-delay")));y++})}function ba(a,b,e){b=parseInt(a.css("margin-left").substr(0,a.css("margin-left").lastIndexOf("px")),10);var m=parseInt(a.css("margin-top").substr(0,a.css("margin-top").lastIndexOf("px")),10),l=0,f=0;a.attr("data-final-left")!=a.attr("data-continuous-left")?b>=l-2&&b<=l+2&&(l=parseInt(a.attr("data-continuous-left")/(e.origWidth/e.width),10)-parseInt(a.attr("data-final-left")/(e.origWidth/
e.width),10),f=parseInt(a.attr("data-continuous-top")/(e.origWidth/e.width),10)-parseInt(a.attr("data-final-top")/(e.origWidth/e.width),10)):a.attr("data-final-top")!=a.attr("data-continuous-top")&&m>=f-2&&m<=f+2&&(l=parseInt(a.attr("data-continuous-left")/(e.origWidth/e.width),10)-parseInt(a.attr("data-final-left")/(e.origWidth/e.width),10),f=parseInt(a.attr("data-continuous-top")/(e.origWidth/e.width),10)-parseInt(a.attr("data-final-top")/(e.origWidth/e.width),10));a.stop().animate({"margin-left":l+
"px","margin-top":f+"px"},1E3*a.attr("data-continuous-duration"),a.attr("data-continuous-easing"),function(){})}function ma(a,b,e,m){var l=0,f=[];d(a.currentImg.attr("data-text-id")).children().each(function(){f[l]=d(this);var k=f[l],h=b.defaultExitLeft;void 0!=k.attr("data-exit-left")&&""!=k.attr("data-exit-left")&&(h=parseInt(k.attr("data-exit-left")/(b.origWidth/b.width),10));var t=b.defaultExitTop;void 0!=k.attr("data-exit-top")&&""!=k.attr("data-exit-top")&&(t=parseInt(k.attr("data-exit-top")/
(b.origWidth/b.width),10));var y=b.defaultExitDuration;void 0!=k.attr("data-exit-duration")&&""!=k.attr("data-exit-duration")&&(y=parseFloat(k.attr("data-exit-duration")));var w=b.defaultExitDelay;void 0!=k.attr("data-exit-delay")&&""!=k.attr("data-exit-delay")&&(w=parseFloat(k.attr("data-exit-delay")));var v=b.defaultExitEasing;void 0!=k.attr("data-exit-easing")&&""!=k.attr("data-exit-easing")&&(v=k.attr("data-exit-easing"));var n=b.defaultExitOFF.toString();void 0!=k.attr("data-exit-off")&&""!=
k.attr("data-exit-off")&&(n=k.attr("data-exit-off"));"true"==n&&(y=0);0<y?a.timeouts_arr[a.timeouts_arr.length]=setTimeout(function(){k.stop().animate({left:h+"px",top:t+"px"},1E3*y,v,function(){"true"!=k.attr("data-preanimate")&&"false"==n?k.css({display:"none"}):(theLeft=k.attr("data-final-left"),theTop=k.attr("data-final-top"),b.responsive&&(theLeft=parseInt(theLeft/(b.origWidth/b.width),10),theTop=parseInt(theTop/(b.origWidth/b.width),10)),k.css({left:theLeft+"px",top:theTop+"px",opacity:1}))})},
1E3*w):"true"!=k.attr("data-preanimate")&&"false"==n&&k.css({display:"none"});l++})}function ca(a,b,e,m){for(var l=0;l<m;l++){e=d(a[l]);var f=[];d(e.attr("data-text-id")).children().each(function(){f[0]=d(this);var k=f[0];if("true"==k.attr("data-preanimate")){k.css({display:"block"});var h=k.attr("data-final-left"),t=k.attr("data-final-top");b.responsive&&(h=parseInt(h/(b.origWidth/b.width),10),t=parseInt(t/(b.origWidth/b.width),10));k.css({left:h+"px",top:t+"px",opacity:1})}else k.css({display:"none"})})}}
function da(a){if(a)for(var b in a)a[b]&&clearTimeout(a[b]);a.length=0}function ea(a){if(a)for(var b in a)a[b]&&clearInterval(a[b]);a.length=0}function na(a,b){if(a)for(var e in a)a[e]&&(a[e]=function(){});a.length=0;b.rotationDurationArr.length=0}function oa(a,b,e,m,l){var f=d(b.attr("data-text-id")).children();if(a.textInPlace.length==f.length&&(0!=m||0!=l)){var k=1,h,t=!0;f.each(function(){h=d(this);t=!0;"false"==h.attr("data-enableMouseInteraction")&&(t=!1);t&&h.stop().animate({left:parseInt(h.attr("data-final-left")/
(e.origWidth/e.width),10)+parseInt(m*k/f.length,10)+"px",top:parseInt(h.attr("data-final-top")/(e.origWidth/e.width),10)+parseInt(l*k/f.length,10)+"px"},{queue:!0,duration:1E3*e.mouseInteractionDuration,easing:e.mouseInteractionEasing},function(){});k++})}}function P(a,b,e,m,l,f,k,h,t,y,w,v,n,G,I,N,x,Q){var z=!0;if(!e.loop&&b.current_img_no+a>=m||!e.loop&&0>b.current_img_no+a)z=!1;if(z&&!b.slideIsRunning&&b.firstLoadingComplete){b.slideIsRunning=!0;da(b.timeouts_arr);ea(b.continuouseIntervalIDs);
na(b.rotationFunctionsArr,b);b.textInPlace.length=0;var A=b.previous_current_img_no;d(b.currentImg.attr("data-text-id")).children().clearQueue();ma(b,e,k,h);e.showCircleTimer&&(b.ctx.clearRect(0,0,b.canvas.width,b.canvas.height),b.ctx.beginPath(),b.ctx.globalAlpha=e.behindCircleAlpha/100,b.ctx.arc(e.circleRadius+2*e.circleLineWidth,e.circleRadius+2*e.circleLineWidth,e.circleRadius,0,2*Math.PI,!1),b.ctx.lineWidth=e.circleLineWidth+2,b.ctx.strokeStyle=e.behindCircleColor,b.ctx.stroke(),b.ctx.beginPath(),
b.ctx.globalAlpha=e.circleAlpha/100,b.ctx.arc(e.circleRadius+2*e.circleLineWidth,e.circleRadius+2*e.circleLineWidth,e.circleRadius,0,0,!1),b.ctx.lineWidth=e.circleLineWidth,b.ctx.strokeStyle=e.circleColor,b.ctx.stroke());"bullets"==e.skin?d(l[b.current_img_no]).removeClass("bottomNavButtonON"):d(v[b.current_img_no]).removeClass("thumbsHolder_ThumbON");w.css("display","none");b.current_img_no=b.current_img_no+a>=m?0:0>b.current_img_no+a?m-1:b.current_img_no+a;e.showBottomNav&&("bullets"==e.skin?(e.autoHideBottomNav||
Q.css("display","block"),d(l[b.current_img_no]).addClass("bottomNavButtonON")):(e.autoHideBottomNav||x.css("display","block"),d(v[b.current_img_no]).addClass("thumbsHolder_ThumbON"),currentCarouselLeft=n.css("left").substr(0,n.css("left").lastIndexOf("px")),0===b.current_img_no||b.current_img_no===m-1?U(0,n,G,I,e,m,N,b):U(1001,n,G,I,e,m,N,b)));b.currentImg=d(f[b.current_img_no]);t.animate({left:-1*b.current_img_no*e.width+"px"},1E3*e.scrollSlideDuration,e.scrollSlideEasing,function(){b.slideIsRunning=
!1;b.arcInitialTime=(new Date).getTime();b.timeElapsed=0;"true"==d(f[b.current_img_no]).attr("data-video")&&w.css("display","block");"true"==d(f[b.previous_current_img_no]).attr("data-video")&&(d("#contentHolderUnit_"+b.previous_current_img_no,y).html(d(f[b.previous_current_img_no]).html()),V(b.previous_current_img_no,b,e,f,y,k,h));da(b.timeouts_arr);T(b,d(f[A]),e,k,y,h,!0);T(b,b.currentImg,e,k,y,h,!1);0<e.autoPlay&&1<m&&!b.mouseOverBanner&&(clearTimeout(b.timeoutID),b.timeoutID=setTimeout(function(){b.previous_current_img_no=
b.current_img_no;P(1,b,e,m,l,f,k,h,t,y,w,v,n,G,I,N,x,Q)},1E3*e.autoPlay))})}}function W(a,b,e,m,l){b=e.origImgsDimensions[b].split(";");m.responsive&&(b[0]/=m.origWidth/m.width,b[1]/=m.origWidth/m.width);a.width(b[0]);a.height(b[1]);l&&m.width100Proc&&m.height100Proc&&a.css({position:"relative",left:parseInt(m.width-a.width(),10)+"px",top:parseInt(m.height-a.height(),10)+"px"})}function V(a,b,e,m,l,f,k){if(e.responsive){var h=d("#contentHolderUnit_"+a,l).find("img:first");null!=h.width()&&W(h,a,b,
e,!0);l=d(d(m[a]).attr("data-text-id")).children();var t=-1;l.each(function(){t++;h=d(this).find("img:first");null!=h.width()&&W(h,d(m[a]).attr("data-text-id")+"-"+t,b,e,!1)});d(d(m[a]).attr("data-text-id")).css({width:e.width+"px",left:parseInt(a*e.width,10),top:k.css("top")})}}function U(a,b,e,m,l,f,k,h){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));1===a||-1===a?(h.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:"+="+a*h.carouselStep},500,"easeOutCubic",
function(){fa(h,b,e,m,l,f,k);h.isCarouselScrolling=!1})):currentCarouselLeft!=-1*Math.floor(h.current_img_no/l.numberOfThumbsPerScreen)*h.carouselStep&&(h.isCarouselScrolling=!0,b.css("opacity","0.5"),b.animate({opacity:1,left:-1*Math.floor(h.current_img_no/l.numberOfThumbsPerScreen)*h.carouselStep},500,"easeOutCubic",function(){fa(h,b,e,m,l,f,k);h.isCarouselScrolling=!1}))}function fa(a,b,e,m,l,f,k){currentCarouselLeft=b.css("left").substr(0,b.css("left").lastIndexOf("px"));0>currentCarouselLeft?
e.hasClass("carouselLeftNavDisabled")&&e.removeClass("carouselLeftNavDisabled"):e.addClass("carouselLeftNavDisabled");Math.abs(currentCarouselLeft-a.carouselStep)<(k.width()+a.thumbMarginLeft)*f?m.hasClass("carouselRightNavDisabled")&&m.removeClass("carouselRightNavDisabled"):m.addClass("carouselRightNavDisabled")}function ha(a,b,e,m,l,f,k,h,t,y,w){"thumbs"==b.skin&&(w.css({bottom:parseInt(b.thumbsWrapperMarginBottom/(b.origWidth/b.width),10)+"px",top:"auto",height:parseInt(b.origthumbsHolderWrapperH/
(b.origWidth/b.width),10)+"px"}),bgTopCorrection=0,k.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),h.css("background-position","0px "+((w.height()-b.origthumbsHolderWrapperH)/2+bgTopCorrection)+"px"),y.css("width",b.width-k.width()-h.width()),b.origWidthThumbsHolderVisibleWrapper=b.origWidth-k.width()-h.width(),l.css({width:parseInt(b.origThumbW/(b.origWidthThumbsHolderVisibleWrapper/y.width()),10)+"px",height:parseInt(b.origThumbH/(b.origWidthThumbsHolderVisibleWrapper/
y.width()),10)+"px"}),b.numberOfThumbsPerScreen>=e&&y.css("left",parseInt((w.width()-(t.width()+a.thumbMarginLeft)*e)/2,10)+"px"),d(".thumbsHolder_ThumbOFF",m).find("img:first").css({width:l.width()+"px",height:l.height()+"px","margin-top":parseInt((w.height()-l.height())/2,10)+"px"}),a.thumbMarginLeft=Math.floor((w.width()-k.width()-h.width()-t.width()*b.numberOfThumbsPerScreen)/(b.numberOfThumbsPerScreen-1)),thumb_i=-1,f.children().each(function(){thumb_i++;theThumb=d(this);theThumb.css("background-position",
"center "+b.thumbsOnMarginTop/(b.origWidth/b.width)+"px");0>=thumb_i?theThumb.css("margin-left",Math.floor((w.width()-k.width()-h.width()-(a.thumbMarginLeft+theThumb.width())*(b.numberOfThumbsPerScreen-1)-theThumb.width())/2)+"px"):theThumb.css("margin-left",a.thumbMarginLeft+"px")}),a.carouselStep=(t.width()+a.thumbMarginLeft)*b.numberOfThumbsPerScreen)}function Y(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));
return parseInt(a,10)}d.fn.parallax_mouseinteraction=function(a){a=d.extend({},d.fn.parallax_mouseinteraction.defaults,a);return this.each(function(){var b=d(this),e=b.parent().width(),m=b.parent().height();a.responsiveRelativeToBrowser&&(e=d(window).width(),m=d(window).height());a.origWidth=a.width;a.width100Proc&&(a.width=e);a.origHeight=a.height;a.height100Proc&&(a.height=m);a.responsive&&(a.origWidth!=e||a.width100Proc)&&(a.width=a.origWidth>e||a.width100Proc?e:a.origWidth,a.height100Proc||(a.height=
a.width/(a.origWidth/a.origHeight)));m=d("<div></div>").addClass("parallax_mouseinteraction").addClass(a.skin);var l=d('<div class="bannerControls">   <div class="leftNav"></div>   <div class="rightNav"></div>    </div>  <div class="contentHolderVisibleWrapper"><div class="contentHolder"></div></div>   <div class="playOver"></div>  <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>  <canvas class="mycanvas"></canvas>');b.wrap(m);b.after(l);
var f=b.parent(".parallax_mouseinteraction");l=d(".bannerControls",f);var k=d(".contentHolderVisibleWrapper",f),h=d(".contentHolder",f);m=d('<div class="bottomNavLeft"></div>');var t=d('<div class="bottomNav"></div>'),y=d('<div class="bottomNavRight"></div>');b.after(m);b.after(t);b.after(y);a.showAllControllers||l.css("display","none");var w=d(".leftNav",f),v=d(".rightNav",f);w.css("display","none");v.css("display","none");a.showNavArrows&&a.showOnInitNavArrows&&(w.css("display","block"),v.css("display",
"block"));var n=d(".bottomNav",f),G=d(".bottomNavLeft",f),I=d(".bottomNavRight",f),N;n.css("display","block");G.css("display","block");I.css("display","block");n.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});G.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});I.css({bottom:parseInt(a.thumbsWrapperMarginBottom/(a.origWidth/a.width),10)+"px",top:"auto"});a.showBottomNav||(n.css("display","none"),G.css("display",
"none"),I.css("display","none"));a.showOnInitBottomNav||(n.css("left","-5000px"),G.css("left","-5000px"),I.css("left","-5000px"));var x=d(".thumbsHolderWrapper",f),Q=d(".thumbsHolderVisibleWrapper",f),z=d(".thumbsHolder",f);var A=d('<div class="carouselLeftNav"></div>');var C=d('<div class="carouselRightNav"></div>');x.append(A);x.append(C);C.css("right","0");z.css("width",A.width()+"px");a.showBottomNav&&a.showOnInitBottomNav||x.css({opacity:0,display:"none"});"thumbs"==a.skin&&x.css({bottom:parseInt(a.thumbsWrapperMarginBottom/
(a.origWidth/a.width),10)+"px",top:"auto"});a.enableTouchScreen&&f.swipe({swipe:function(g,p,D,q,J){c.effectIsRunning||("right"==p?w.click():v.click())}});var E=d(".playOver",f);E.css({left:parseInt((a.width-E.width())/2,10)+"px",top:parseInt((a.height-E.height())/2,10)+"px"});d(".myloader",f).css({left:(a.width-d(".myloader",f).width())/2+"px",top:(a.height-d(".myloader",f).height())/2+"px"});m=Y();var u=0,c={current_img_no:0,currentImg:0,previous_current_img_no:0,slideIsRunning:!1,mouseOverBanner:!1,
isVideoPlaying:!1,carouselStep:0,thumbMarginLeft:0,timeoutID:"",intervalID:"",arcInitialTime:(new Date).getTime(),timeElapsed:0,windowWidth:0,origImgsDimensions:[],firstLoadingComplete:!1,canvas:"",ctx:"",timeouts_arr:[],continuouseIntervalIDs:[],rotationFunctionsArr:[],rotationDurationArr:[],textInPlace:[],prevMouseX:0,prevMouseY:0,bannerRatio:a.origWidth/a.origHeight},Z=0;c.canvas=d(".mycanvas",f)[0];c.canvas.width=2*a.circleRadius+4*a.circleLineWidth;c.canvas.height=2*a.circleRadius+4*a.circleLineWidth;
-1!=m&&9>m&&(a.showCircleTimer=!1);a.showCircleTimer&&(c.ctx=c.canvas.getContext("2d"));f.width(a.width);f.height(a.height);k.width(a.width);k.height(a.height);h.width(a.width);h.height(a.height);l.css("margin-top",parseInt((a.height-w.height())/2,10)+"px");a.centerPlugin&&f.css({margin:"0 auto"});var r=b.find("ul:first").children(),ia=0,K,B,X=0,ja=0,H;r.each(function(){c.currentImg=d(this);c.currentImg.is("li")||(c.currentImg=c.currentImg.find("li:first"));if(c.currentImg.is("li")){u++;S=d('<div class="contentHolderUnit" rel="'+
(u-1)+'" id="contentHolderUnit_'+(u-1)+'">'+c.currentImg.html()+"</div>");S.width(a.width);S.height(a.height);h.append(S);ia+=a.width;H=d("#contentHolderUnit_"+(u-1),f).find("img:first");null!=H.width()?(c.origImgsDimensions[u-1]=H.width()+";"+H.height(),a.responsive&&a.origWidth!=e&&W(H,u-1,c,a,!0)):c.origImgsDimensions[u-1]=null;"bullets"==a.skin?(K=d('<div class="bottomNavButtonOFF" rel="'+(u-1)+'"></div>'),n.append(K),X+=parseInt(K.css("padding-left").substring(0,K.css("padding-left").length-
2),10)+K.width(),ja=parseInt((n.height()-parseInt(K.css("height").substring(0,K.css("height").length-2)))/2,10),K.css("margin-top",ja+"px")):(image_name=d(r[u-1]).attr("data-bottom-thumb"),B=d('<div class="thumbsHolder_ThumbOFF" rel="'+(u-1)+'"><img src="'+image_name+'"></div>'),z.append(B),0==a.origThumbW&&(0==a.numberOfThumbsPerScreen&&(a.numberOfThumbsPerScreen=Math.floor((a.origWidth-A.width()-C.width())/B.width())),a.origThumbW=B.width(),a.origThumbH=B.height(),a.origthumbsHolderWrapperH=x.height(),
c.thumbMarginLeft=Math.floor((a.origWidth-A.width()-C.width()-B.width()*a.numberOfThumbsPerScreen)/(a.numberOfThumbsPerScreen-1))),z.css("width",z.width()+c.thumbMarginLeft+B.width()+"px"),thumbsHolder_MarginTop=parseInt((x.height()-parseInt(B.css("height").substring(0,B.css("height").length-2)))/2,10));h.append(d(c.currentImg.attr("data-text-id")));d(c.currentImg.attr("data-text-id")).css({width:a.width+"px",height:"100%",overflow:"hidden",left:parseInt((u-1)*a.width,10),top:l.css("top")});var g=
-1;d(c.currentImg.attr("data-text-id")).children().each(function(){g++;H=d(this).find("img:first");null!=H.width()?(c.origImgsDimensions[c.currentImg.attr("data-text-id")+"-"+g]=H.width()+";"+H.height(),a.responsive&&a.origWidth!=e&&W(H,c.currentImg.attr("data-text-id")+"-"+g,c,a,!1)):c.origImgsDimensions[c.currentImg.attr("data-text-id")+"-"+g]=null})}});h.width(ia);"bullets"==a.skin?(n.width(X),a.showOnInitBottomNav&&(n.css("left",parseInt((f.width()-X)/2,10)+"px"),G.css("left",parseInt(n.css("left").substring(0,
n.css("left").length-2),10)-G.width()+"px"),I.css("left",parseInt(n.css("left").substring(0,n.css("left").length-2),10)+n.width()+parseInt(K.css("padding-left").substring(0,K.css("padding-left").length-2),10)+"px"))):(Q.css({width:a.origWidth-A.width()-C.width(),left:A.width()+"px"}),c.carouselStep=(B.width()+c.thumbMarginLeft)*a.numberOfThumbsPerScreen,A.addClass("carouselLeftNavDisabled"),a.numberOfThumbsPerScreen>=u&&(C.addClass("carouselRightNavDisabled"),A.css("display","none"),C.css("display",
"none"),Q.css("left",parseInt((x.width()-(B.width()+c.thumbMarginLeft)*u)/2,10)+"px")),d(".thumbsHolder_ThumbOFF",f).find("img:first").css("margin-top",thumbsHolder_MarginTop+"px"),a.origthumbsHolder_MarginTop=thumbsHolder_MarginTop);var F=d(".thumbsHolder_ThumbOFF",f);ha(c,a,u,f,F,z,A,C,B,Q,x);1>=u&&(a.showAllControllers=!1,l.css("display","none"),"bullets"==a.skin?(n.css("display","none"),G.css("display","none"),I.css("display","none")):Q.css("display","none"),a.enableTouchScreen=!1,h.css({cursor:"default"}));
d("iframe",f).each(function(){var g=d(this).attr("src"),p="?wmode=transparent";-1!=g.indexOf("?")&&(p="&wmode=transparent");d(this).attr("src",g+p)});c.current_img_no=0;c.currentImg=d(r[0]);f.mousemove(function(g){if(a.enableMouseInteraction){var p=parseInt(a.width/2,10),D=parseInt(a.height/2,10),q=parseInt(a.maxInteractionXmove/(a.origWidth/a.width)),J=parseInt(a.maxInteractionYmove/(a.origWidth/a.width));var M=g.pageX-f.position().left-p;g=g.pageY-f.position().top-D;M=parseInt(M*q/p);g=parseInt(g*
J/D);oa(c,c.currentImg,a,M,g)}});f.mouseenter(function(){if(a.pauseOnMouseOver&&1<u&&c.firstLoadingComplete){c.mouseOverBanner=!0;clearTimeout(c.timeoutID);var g=(new Date).getTime();c.timeElapsed+=g-c.arcInitialTime}a.autoHideNavArrows&&a.showNavArrows&&(w.css("display","block"),v.css("display","block"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(n.css({display:"block",left:parseInt((f.width()-X)/2,10)+"px"}),G.css({display:"block",left:parseInt(n.css("left").substring(0,n.css("left").length-
2),10)-G.width()+"px"}),I.css({display:"block",left:parseInt(n.css("left").substring(0,n.css("left").length-2),10)+n.width()+parseInt(K.css("padding-left").substring(0,K.css("padding-left").length-2),10)+"px"})):0>a.thumbsWrapperMarginBottom&&c.isVideoPlaying||!a.showBottomNav||(x.css({display:"block"}),x.stop().animate({opacity:1},500,"swing",function(){})))});f.mouseleave(function(){a.pauseOnMouseOver&&1<u&&c.firstLoadingComplete&&(c.mouseOverBanner=!1);a.autoHideNavArrows&&a.showNavArrows&&(w.css("display",
"none"),v.css("display","none"));a.autoHideBottomNav&&a.showBottomNav&&("bullets"==a.skin?(n.css("display","none"),G.css("display","none"),I.css("display","none")):x.stop().animate({opacity:0},300,"swing",function(){}));if(0<a.autoPlay&&1<u&&!c.isVideoPlaying&&a.pauseOnMouseOver&&c.firstLoadingComplete){clearTimeout(c.timeoutID);var g=(new Date).getTime();c.arcInitialTime=(new Date).getTime();g=parseInt(1E3*a.autoPlay-(c.timeElapsed+g-c.arcInitialTime),10);c.timeoutID=setTimeout(function(){P(1,c,
a,u,L,r,b,l,h,f,E,F,z,A,C,B,x,n)},g)}});var S=d(".contentHolderUnit",h);S.click(function(){var g=d(this).attr("rel");"true"==d(r[c.current_img_no]).attr("data-video")&&(g!=c.current_img_no?c.isVideoPlaying=!1:(clearTimeout(c.timeoutID),H=d(this).find("img:first"),H.css("display","none"),E.css("display","none"),c.isVideoPlaying=!0,"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&x.css("display","none"),"bullets"==a.skin&&0<=a.thumbsWrapperMarginBottom&&n.css("display","none")));
void 0!=d(r[c.current_img_no]).attr("data-link")&&g==c.current_img_no&&""!=d(r[c.current_img_no]).attr("data-link")&&(g=a.target,void 0!=d(r[c.current_img_no]).attr("data-target")&&""!=d(r[c.current_img_no]).attr("data-target")&&(g=d(r[c.current_img_no]).attr("data-target")),"_blank"==g?window.open(d(r[c.current_img_no]).attr("data-link")):window.location=d(r[c.current_img_no]).attr("data-link"))});E.click(function(){E.css("display","none");clearTimeout(c.timeoutID);H=d("#contentHolderUnit_"+c.current_img_no,
f).find("img:first");H.css("display","none");c.isVideoPlaying=!0;"thumbs"==a.skin&&a.thumbsWrapperMarginBottom>-1*a.origthumbsHolderWrapperH&&x.css("display","none");"bullets"==a.skin&&0<=a.thumbsWrapperMarginBottom&&n.css("display","none")});d(".parallax_mouseinteraction_texts",f).click(function(){if(void 0!=d(r[c.current_img_no]).attr("data-link")&&""!=d(r[c.current_img_no]).attr("data-link")&&!c.slideIsRunning){var g=a.target;void 0!=d(r[c.current_img_no]).attr("data-target")&&""!=d(r[c.current_img_no]).attr("data-target")&&
(g=d(r[c.current_img_no]).attr("data-target"));"_blank"==g?window.open(d(r[c.current_img_no]).attr("data-link")):window.location=d(r[c.current_img_no]).attr("data-link")}});w.click(function(){c.slideIsRunning||(c.isVideoPlaying=!1,c.previous_current_img_no=c.current_img_no,clearTimeout(c.timeoutID),P(-1,c,a,u,L,r,b,l,h,f,E,F,z,A,C,B,x,n))});v.click(function(){c.slideIsRunning||(c.isVideoPlaying=!1,c.previous_current_img_no=c.current_img_no,clearTimeout(c.timeoutID),P(1,c,a,u,L,r,b,l,h,f,E,F,z,A,C,
B,x,n))});var aa=!1;d(window).resize(function(){var g=Y(),p=!0;-1!=navigator.userAgent.indexOf("Android")&&(0==a.windowOrientationScreenSize0&&0==window.orientation&&(a.windowOrientationScreenSize0=d(window).width()),0==a.windowOrientationScreenSize90&&90==window.orientation&&(a.windowOrientationScreenSize90=d(window).height()),0==a.windowOrientationScreenSize_90&&-90==window.orientation&&(a.windowOrientationScreenSize_90=d(window).height()),a.windowOrientationScreenSize0&&0==window.orientation&&
d(window).width()>a.windowOrientationScreenSize0&&(p=!1),a.windowOrientationScreenSize90&&90==window.orientation&&d(window).height()>a.windowOrientationScreenSize90&&(p=!1),a.windowOrientationScreenSize_90&&-90==window.orientation&&d(window).height()>a.windowOrientationScreenSize_90&&(p=!1),0==c.windowWidth&&(p=!1,c.windowWidth=d(window).width()));-1!=g&&9==g&&0==c.windowWidth&&(p=!1);c.windowWidth==d(window).width()?(p=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&
(a.windowCurOrientation=window.orientation,p=!0)):c.windowWidth=d(window).width();a.responsive&&p&&(!1!==aa&&clearTimeout(aa),aa=setTimeout(function(){var D=c,q=a,J=u,M=l,pa=L,ka=B,O=b.parent().parent().width(),R=b.parent().parent().height();q.responsiveRelativeToBrowser&&(O=d(window).width(),R=d(window).height());q.width100Proc&&(q.width=O);q.height100Proc&&(q.height=R);if(q.origWidth!=O||q.width100Proc){q.origWidth>O||q.width100Proc?q.width=O:q.width100Proc||(q.width=q.origWidth);q.height100Proc||
(q.height=q.width/D.bannerRatio);f.width(q.width);f.height(q.height);k.width(q.width);k.height(q.height);h.width(q.width);h.height(q.height);M.css("margin-top",parseInt((q.height-w.height())/2,10)+"px");ca(r,q,b,J);O=d(".contentHolderUnit",f);O.width(q.width);O.height(q.height);O=q.width*J;for(R=0;R<J;R++)V(R,D,q,r,f,b,M);h.width(O);"bullets"==q.skin?0<=q.thumbsWrapperMarginBottom?n.css({left:parseInt((f.width()-n.width())/2,10)+"px",bottom:parseInt(q.thumbsWrapperMarginBottom/(q.origWidth/q.width),
10)+"px",top:"auto"}):n.css({left:parseInt((f.width()-n.width())/2,10)+"px"}):ha(D,q,J,f,F,z,A,C,ka,Q,x);E.css({left:parseInt((q.width-E.width())/2,10)+"px",top:parseInt((q.height-E.height())/2,10)+"px"});clearTimeout(D.timeoutID);ea(D.continuouseIntervalIDs);2>J?(d(".newFS",f).contents().unwrap(),T(D,D.currentImg,q,b,f,M,!1)):P(1,D,q,J,pa,r,b,M,h,f,E,F,z,A,C,ka,x,n)}},300))});if("bullets"==a.skin){var L=d(".bottomNavButtonOFF",f);L.click(function(){if(!c.slideIsRunning&&c.firstLoadingComplete){c.isVideoPlaying=
!1;var g=d(this).attr("rel");c.current_img_no!=g&&(d(L[c.current_img_no]).removeClass("bottomNavButtonON"),c.previous_current_img_no=c.current_img_no,"true"==d(r[c.previous_current_img_no]).attr("data-video")&&(d("#contentHolderUnit_"+c.previous_current_img_no,f).html(d(r[c.previous_current_img_no]).html()),V(c.previous_current_img_no,c,a,r,f,b,l)),c.current_img_no=g-1,P(1,c,a,u,L,r,b,l,h,f,E,F,z,A,C,B,x,n))}});L.mouseenter(function(){var g=d(this),p=g.attr("rel");if(a.showPreviewThumbs){N=d('<div class="bottomOverThumb"></div>');
g.append(N);var D=d(r[p]).attr("data-bottom-thumb"),q=d(r[Z]).attr("data-bottom-thumb"),J=80,M=-80;Z>p&&(J=-80,M=80);N.html("");N.html('<div class="innerBottomOverThumb"><img src="'+q+'"style="margin:0px;" id="oldThumb"><img src="'+D+'" style="margin-top:-80px; margin-left:'+J+'px;" id="newThumb"></div>');d("#newThumb").stop().animate({marginLeft:"0px"},150,function(){N.html('<div class="innerBottomOverThumb"><img src="'+D+'"></div>')});d("#oldThumb").stop().animate({marginLeft:M+"px"},150,function(){});
Z=p}g.addClass("bottomNavButtonON")});L.mouseleave(function(){var g=d(this),p=g.attr("rel");a.showPreviewThumbs&&N.remove();c.current_img_no!=p&&g.removeClass("bottomNavButtonON")})}F.mousedown(function(){arrowClicked=!0;if(!c.effectIsRunning&&c.firstLoadingComplete){c.isVideoPlaying=!1;var g=d(this).attr("rel");c.current_img_no!=g&&(d(F[c.current_img_no]).removeClass("thumbsHolder_ThumbON"),c.previous_current_img_no=c.current_img_no,"true"==d(r[c.previous_current_img_no]).attr("data-video")&&(d("#contentHolderUnit_"+
c.previous_current_img_no,f).html(d(r[c.previous_current_img_no]).html()),V(c.previous_current_img_no,c,a,r,f,b,l)),c.bottomNavClicked=!0,c.current_img_no=g-1,P(1,c,a,u,L,r,b,l,h,f,E,F,z,A,C,B,x,n))}});F.mouseup(function(){arrowClicked=!1});F.mouseenter(function(){var g=d(this);g.attr("rel");g.addClass("thumbsHolder_ThumbON")});F.mouseleave(function(){var g=d(this),p=g.attr("rel");c.current_img_no!=p&&g.removeClass("thumbsHolder_ThumbON")});A.click(function(){c.isCarouselScrolling||(currentCarouselLeft=
z.css("left").substr(0,z.css("left").lastIndexOf("px")),0>currentCarouselLeft&&U(1,z,A,C,a,u,B,c))});C.click(function(){c.isCarouselScrolling||(currentCarouselLeft=z.css("left").substr(0,z.css("left").lastIndexOf("px")),Math.abs(currentCarouselLeft-c.carouselStep)<(B.width()+c.thumbMarginLeft)*u&&U(-1,z,A,C,a,u,B,c))});"bullets"==a.skin?d(L[c.current_img_no]).addClass("bottomNavButtonON"):d(F[c.current_img_no]).addClass("thumbsHolder_ThumbON");setTimeout(function(){d(".myloader",f).css("display",
"none");ca(r,a,b,u);c.firstLoadingComplete=!0;1<u&&(c.arcInitialTime=(new Date).getTime(),c.mouseOverBanner=!1,c.timeElapsed=0);T(c,c.currentImg,a,b,f,l,!1,c.current_img_no);0<a.autoPlay&&1<u&&(a.showCircleTimer&&(c.intervalID=setInterval(function(){var g=c,p=a,D=(new Date).getTime();g.mouseOverBanner||g.effectIsRunning||!p.showCircleTimer||g.slideIsRunning||(g.ctx.clearRect(0,0,g.canvas.width,g.canvas.height),g.ctx.beginPath(),g.ctx.globalAlpha=p.behindCircleAlpha/100,g.ctx.arc(p.circleRadius+2*
p.circleLineWidth,p.circleRadius+2*p.circleLineWidth,p.circleRadius,0,2*Math.PI,!1),g.ctx.lineWidth=p.circleLineWidth+2,g.ctx.strokeStyle=p.behindCircleColor,g.ctx.stroke(),g.ctx.beginPath(),g.ctx.globalAlpha=p.circleAlpha/100,g.ctx.arc(p.circleRadius+2*p.circleLineWidth,p.circleRadius+2*p.circleLineWidth,p.circleRadius,0,(g.timeElapsed+D-g.arcInitialTime)/1E3*2/p.autoPlay*Math.PI,!1),g.ctx.lineWidth=p.circleLineWidth,g.ctx.strokeStyle=p.circleColor,g.ctx.stroke())},125)),c.timeoutID=setTimeout(function(){P(1,
c,a,u,L,r,b,l,h,f,E,F,z,A,C,B,x,n)},1E3*a.autoPlay))},1E3*a.myloaderTime);"true"==d(r[c.current_img_no]).attr("data-video")&&E.css("display","block")})};d.fn.parallax_mouseinteraction.defaults={skin:"bullets",width:918,height:382,width100Proc:!1,height100Proc:!1,autoPlay:7,loop:!0,target:"_blank",absUrl:"",showAllControllers:!0,showNavArrows:!0,showOnInitNavArrows:!0,autoHideNavArrows:!0,showBottomNav:!0,showOnInitBottomNav:!0,autoHideBottomNav:!0,showPreviewThumbs:!0,enableTouchScreen:!0,pauseOnMouseOver:!0,
showCircleTimer:!0,showCircleTimerIE8IE7:!1,circleRadius:10,circleLineWidth:4,circleColor:"#FF0000",circleAlpha:100,behindCircleColor:"#000000",behindCircleAlpha:50,responsive:!0,responsiveRelativeToBrowser:!1,centerPlugin:!1,thumbsWrapperMarginBottom:-35,scrollSlideDuration:.8,scrollSlideEasing:"easeOutQuad",numberOfThumbsPerScreen:0,thumbsOnMarginTop:10,defaultEasing:"swing",myloaderTime:4,defaultExitLeft:0,defaultExitTop:0,defaultExitDuration:0,defaultExitDelay:0,defaultExitEasing:"swing",defaultExitOFF:!1,
enableMouseInteraction:!0,maxInteractionXmove:70,maxInteractionYmove:40,mouseInteractionEasing:"easeOutQuint",mouseInteractionDuration:1,origWidth:0,origHeight:0,origThumbW:0,origThumbH:0,origthumbsHolderWrapperH:0,origWidthThumbsHolderVisibleWrapper:0,windowOrientationScreenSize0:0,windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
